# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.models.participant import Participant

class TestParticipant(unittest.TestCase):
    """Participant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Participant:
        """Test Participant
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Participant`
        """
        model = Participant()
        if include_optional:
            return Participant(
                club_member = True,
                display_username = True,
                full_name = 'Brian Lara',
                id = 26518181881,
                is_registered = False,
                is_substitute = False,
                is_wait_listed = False,
                partner_status = 'NOT_ADDED/CONFIRMED/NOT_CONFIRMED/PAYMENT_DUE',
                payment_due = '2021-12-01',
                payment_refunded = False,
                payment_status = 'PENDING/COMPLETE',
                refund_amount = 1.337,
                status = 'NOT_ADDED/CONFIRMED/NOT_CONFIRMED/PAYMENT_DUE',
                username = 'X AE A-XII'
            )
        else:
            return Participant(
                club_member = True,
                full_name = 'Brian Lara',
                is_substitute = False,
                is_wait_listed = False,
                payment_refunded = False,
                refund_amount = 1.337,
        )
        """

    def testParticipant(self):
        """Test Participant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
