# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.api.users_api import UsersApi


class TestUsersApi(unittest.IsolatedAsyncioTestCase):
    """UsersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UsersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_user_provisional_rating_using_post(self) -> None:
        """Test case for create_user_provisional_rating_using_post

        Set the provisional rating for a player
        """
        pass

    async def test_delete_user_provisional_rating_using_delete(self) -> None:
        """Test case for delete_user_provisional_rating_using_delete

        Delete the provisional rating for a player
        """
        pass

    async def test_get_club_membership_by_dupr_id_using_get(self) -> None:
        """Test case for get_club_membership_by_dupr_id_using_get

        Retrieve the club membership for a user by DUPR Id
        """
        pass

    async def test_get_user_provisional_rating_using_post(self) -> None:
        """Test case for get_user_provisional_rating_using_post

        Get the provisional rating for a player
        """
        pass

    async def test_invite_user_using_post(self) -> None:
        """Test case for invite_user_using_post

        Pre-generate a dupr ID and invite a user to join
        """
        pass

    async def test_update_user_provisional_rating_using_post(self) -> None:
        """Test case for update_user_provisional_rating_using_post

        Set the provisional rating for a player
        """
        pass

    async def test_user_detail_using_get(self) -> None:
        """Test case for user_detail_using_get

        User Info
        """
        pass

    async def test_user_search_using_post(self) -> None:
        """Test case for user_search_using_post

        User Search
        """
        pass


if __name__ == '__main__':
    unittest.main()
