# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.models.external_filter_location import ExternalFilterLocation

class TestExternalFilterLocation(unittest.TestCase):
    """ExternalFilterLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalFilterLocation:
        """Test ExternalFilterLocation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalFilterLocation`
        """
        model = ExternalFilterLocation()
        if include_optional:
            return ExternalFilterLocation(
                address = 'Austin, TX, USA',
                lat = 72.34654645455,
                lng = 19.55151584984,
                radius_in_meters = 40233.6
            )
        else:
            return ExternalFilterLocation(
                address = 'Austin, TX, USA',
                lat = 72.34654645455,
                lng = 19.55151584984,
                radius_in_meters = 40233.6,
        )
        """

    def testExternalFilterLocation(self):
        """Test ExternalFilterLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
