# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.models.external_user_rating_response import ExternalUserRatingResponse

class TestExternalUserRatingResponse(unittest.TestCase):
    """ExternalUserRatingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalUserRatingResponse:
        """Test ExternalUserRatingResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalUserRatingResponse`
        """
        model = ExternalUserRatingResponse()
        if include_optional:
            return ExternalUserRatingResponse(
                doubles = '2.864',
                doubles_half_life = 20.14,
                doubles_reliability_score = 2.5,
                is_doubles_reliable = False,
                is_singles_reliable = True,
                provisional_ratings = dupr_prod_httpx.models.provisional_rating.ProvisionalRating(
                    coach = dupr_prod_httpx.models.rating_coach.RatingCoach(
                        id = '', 
                        metadata = {
                            'key' : ''
                            }, ), 
                    doubles_rating = 3.5, 
                    singles_rating = 3.5, ),
                singles = '4.125',
                singles_half_life = 15.05,
                singles_reliability_score = 2.5
            )
        else:
            return ExternalUserRatingResponse(
        )
        """

    def testExternalUserRatingResponse(self):
        """Test ExternalUserRatingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
