# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.models.array_wrapper_of_external_user_detail_response import ArrayWrapperOfExternalUserDetailResponse

class TestArrayWrapperOfExternalUserDetailResponse(unittest.TestCase):
    """ArrayWrapperOfExternalUserDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArrayWrapperOfExternalUserDetailResponse:
        """Test ArrayWrapperOfExternalUserDetailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArrayWrapperOfExternalUserDetailResponse`
        """
        model = ArrayWrapperOfExternalUserDetailResponse()
        if include_optional:
            return ArrayWrapperOfExternalUserDetailResponse(
                message = 'Show this message to user.',
                results = [
                    dupr_prod_httpx.models.external_user_detail_response.ExternalUserDetailResponse(
                        first_name = 'John', 
                        full_name = 'John Doe', 
                        id = 'XOME32', 
                        last_name = 'Doe', 
                        performance = dupr_prod_httpx.models.external_user_performance.ExternalUserPerformance(
                            doubles = dupr_prod_httpx.models.win_loss_count.WinLossCount(
                                loss = 21, 
                                total = 33, 
                                win = 12, ), 
                            singles = dupr_prod_httpx.models.win_loss_count.WinLossCount(
                                loss = 21, 
                                total = 33, 
                                win = 12, ), ), 
                        ratings = dupr_prod_httpx.models.ratings.ratings(), )
                    ],
                status = 'FAILURE'
            )
        else:
            return ArrayWrapperOfExternalUserDetailResponse(
        )
        """

    def testArrayWrapperOfExternalUserDetailResponse(self):
        """Test ArrayWrapperOfExternalUserDetailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
