# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.api.player_rating_api import PlayerRatingApi


class TestPlayerRatingApi(unittest.IsolatedAsyncioTestCase):
    """PlayerRatingApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PlayerRatingApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_client_players_subscription_using_get(self) -> None:
        """Test case for get_client_players_subscription_using_get

        Fetch Players subscription by Client
        """
        pass

    async def test_get_player_rating_history_by_user_using_post(self) -> None:
        """Test case for get_player_rating_history_by_user_using_post

        getPlayerRatingHistoryByUser
        """
        pass

    async def test_remove_player_subscription_using_delete(self) -> None:
        """Test case for remove_player_subscription_using_delete

        Removes players rating
        """
        pass

    async def test_subscribe_player_rating_using_post(self) -> None:
        """Test case for subscribe_player_rating_using_post

        Subscribe players rating
        """
        pass


if __name__ == '__main__':
    unittest.main()
