# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.api.match_api import MatchApi


class TestMatchApi(unittest.IsolatedAsyncioTestCase):
    """MatchApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = MatchApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_delete_match_using_delete(self) -> None:
        """Test case for delete_match_using_delete

        Delete Match
        """
        pass

    async def test_save_match_in_bulk_using_post(self) -> None:
        """Test case for save_match_in_bulk_using_post

        Create Match in Bulk
        """
        pass

    async def test_save_match_using_post(self) -> None:
        """Test case for save_match_using_post

        Create Match
        """
        pass

    async def test_search_match_history_using_post(self) -> None:
        """Test case for search_match_history_using_post

        Get Match History
        """
        pass

    async def test_update_match_using_post(self) -> None:
        """Test case for update_match_using_post

        Update a match
        """
        pass

    async def test_view_match_using_get(self) -> None:
        """Test case for view_match_using_get

        viewMatch
        """
        pass


if __name__ == '__main__':
    unittest.main()
