# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.api.api_registration_api import ApiRegistrationApi


class TestApiRegistrationApi(unittest.IsolatedAsyncioTestCase):
    """ApiRegistrationApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ApiRegistrationApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_all_using_get(self) -> None:
        """Test case for get_all_using_get

        getAll
        """
        pass

    async def test_register_using_post(self) -> None:
        """Test case for register_using_post

        register
        """
        pass


if __name__ == '__main__':
    unittest.main()
