# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.models.external_search_request import ExternalSearchRequest

class TestExternalSearchRequest(unittest.TestCase):
    """ExternalSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalSearchRequest:
        """Test ExternalSearchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalSearchRequest`
        """
        model = ExternalSearchRequest()
        if include_optional:
            return ExternalSearchRequest(
                filters = dupr_prod_httpx.models.external_search_filter.ExternalSearchFilter(
                    age = dupr_prod_httpx.models.external_age_range_filter.ExternalAgeRangeFilter(
                        max = 25, 
                        min = 18, ), 
                    gender = 'MALE', 
                    location = dupr_prod_httpx.models.external_filter_location.ExternalFilterLocation(
                        address = 'Austin, TX, USA', 
                        lat = 72.34654645455, 
                        lng = 19.55151584984, 
                        radius_in_meters = 40233.6, ), 
                    rating = dupr_prod_httpx.models.external_rating_filter.ExternalRatingFilter(
                        max = 3.3, 
                        min = 2.3, 
                        reliable = True, 
                        type = 'DOUBLES', ), ),
                limit = 25,
                offset = 0,
                query = '*'
            )
        else:
            return ExternalSearchRequest(
                limit = 25,
                offset = 0,
                query = '*',
        )
        """

    def testExternalSearchRequest(self):
        """Test ExternalSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
