# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.models.external_club_member_request import ExternalClubMemberRequest

class TestExternalClubMemberRequest(unittest.TestCase):
    """ExternalClubMemberRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalClubMemberRequest:
        """Test ExternalClubMemberRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalClubMemberRequest`
        """
        model = ExternalClubMemberRequest()
        if include_optional:
            return ExternalClubMemberRequest(
                club_id = 102387102937
            )
        else:
            return ExternalClubMemberRequest(
                club_id = 102387102937,
        )
        """

    def testExternalClubMemberRequest(self):
        """Test ExternalClubMemberRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
