# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.models.external_match_search_request import ExternalMatchSearchRequest

class TestExternalMatchSearchRequest(unittest.TestCase):
    """ExternalMatchSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalMatchSearchRequest:
        """Test ExternalMatchSearchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalMatchSearchRequest`
        """
        model = ExternalMatchSearchRequest()
        if include_optional:
            return ExternalMatchSearchRequest(
                dupr_id = 'KJHFAH',
                end_date = 1724100043,
                event_format = [SINGLES, DOUBLES],
                limit = 3,
                offset = 0,
                start_date = 1724099943
            )
        else:
            return ExternalMatchSearchRequest(
                end_date = 1724100043,
                start_date = 1724099943,
        )
        """

    def testExternalMatchSearchRequest(self):
        """Test ExternalMatchSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
