# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.models.provisional_rating import ProvisionalRating

class TestProvisionalRating(unittest.TestCase):
    """ProvisionalRating unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProvisionalRating:
        """Test ProvisionalRating
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProvisionalRating`
        """
        model = ProvisionalRating()
        if include_optional:
            return ProvisionalRating(
                coach = dupr_prod_httpx.models.rating_coach.RatingCoach(
                    id = '', 
                    metadata = {
                        'key' : ''
                        }, ),
                doubles_rating = 3.5,
                singles_rating = 3.5
            )
        else:
            return ProvisionalRating(
        )
        """

    def testProvisionalRating(self):
        """Test ProvisionalRating"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
