# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.api.player_api import PlayerApi


class TestPlayerApi(unittest.IsolatedAsyncioTestCase):
    """PlayerApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PlayerApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_player_duprid_by_email_using_post(self) -> None:
        """Test case for get_player_duprid_by_email_using_post

        Get DUPR ID by Email
        """
        pass

    async def test_get_rank_of_players_using_post(self) -> None:
        """Test case for get_rank_of_players_using_post

        Players Rating
        """
        pass


if __name__ == '__main__':
    unittest.main()
