# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.models.external_rating_filter import ExternalRatingFilter

class TestExternalRatingFilter(unittest.TestCase):
    """ExternalRatingFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalRatingFilter:
        """Test ExternalRatingFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalRatingFilter`
        """
        model = ExternalRatingFilter()
        if include_optional:
            return ExternalRatingFilter(
                max = 3.3,
                min = 2.3,
                reliable = True,
                type = 'DOUBLES'
            )
        else:
            return ExternalRatingFilter(
                max = 3.3,
                min = 2.3,
        )
        """

    def testExternalRatingFilter(self):
        """Test ExternalRatingFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
