# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.api.club_api import ClubApi


class TestClubApi(unittest.IsolatedAsyncioTestCase):
    """ClubApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ClubApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_club_members_rating_using_post(self) -> None:
        """Test case for club_members_rating_using_post

        Club Members Rating
        """
        pass


if __name__ == '__main__':
    unittest.main()
