# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_prod_httpx.models.external_match_team import ExternalMatchTeam

class TestExternalMatchTeam(unittest.TestCase):
    """ExternalMatchTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalMatchTeam:
        """Test ExternalMatchTeam
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalMatchTeam`
        """
        model = ExternalMatchTeam()
        if include_optional:
            return ExternalMatchTeam(
                game1 = 7,
                game2 = 11,
                game3 = 0,
                game4 = 0,
                game5 = 0,
                player1 = 'L8EW8W',
                player2 = 'O8GJV8'
            )
        else:
            return ExternalMatchTeam(
                game1 = 7,
                player1 = 'L8EW8W',
        )
        """

    def testExternalMatchTeam(self):
        """Test ExternalMatchTeam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
