# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ExternalMatchTeam(BaseModel):
    """
    ExternalMatchTeam
    """ # noqa: E501
    game1: StrictInt = Field(description="Team's Game 1 score")
    game2: Optional[StrictInt] = Field(default=None, description="Team's Game 2 score")
    game3: Optional[StrictInt] = Field(default=None, description="Team's Game 3 score")
    game4: Optional[StrictInt] = Field(default=None, description="Team's Game 4 score")
    game5: Optional[StrictInt] = Field(default=None, description="Team's Game 5 score")
    player1: StrictStr = Field(description="DUPR ID of player 1")
    player2: Optional[StrictStr] = Field(default=None, description="DUPR ID of player 2, in case of singles it can be null")
    __properties: ClassVar[List[str]] = ["game1", "game2", "game3", "game4", "game5", "player1", "player2"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalMatchTeam from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalMatchTeam from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "game1": obj.get("game1"),
            "game2": obj.get("game2"),
            "game3": obj.get("game3"),
            "game4": obj.get("game4"),
            "game5": obj.get("game5"),
            "player1": obj.get("player1"),
            "player2": obj.get("player2")
        })
        return _obj


