# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from dupr_prod_httpx.models.external_age_range_filter import ExternalAgeRangeFilter
from dupr_prod_httpx.models.external_filter_location import ExternalFilterLocation
from dupr_prod_httpx.models.external_rating_filter import ExternalRatingFilter
from typing import Optional, Set
from typing_extensions import Self

class ExternalSearchFilter(BaseModel):
    """
    ExternalSearchFilter
    """ # noqa: E501
    age: Optional[ExternalAgeRangeFilter] = None
    gender: Optional[Annotated[str, Field(min_length=4, strict=True, max_length=6)]] = Field(default=None, description="Value must be exact match from the following array.")
    location: Optional[ExternalFilterLocation] = None
    rating: Optional[ExternalRatingFilter] = None
    __properties: ClassVar[List[str]] = ["age", "gender", "location", "rating"]

    @field_validator('gender')
    def gender_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(?:male|female)$", value):
            raise ValueError(r"must validate the regular expression /^(?:male|female)$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalSearchFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of age
        if self.age:
            _dict['age'] = self.age.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rating
        if self.rating:
            _dict['rating'] = self.rating.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalSearchFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "age": ExternalAgeRangeFilter.from_dict(obj["age"]) if obj.get("age") is not None else None,
            "gender": obj.get("gender"),
            "location": ExternalFilterLocation.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "rating": ExternalRatingFilter.from_dict(obj["rating"]) if obj.get("rating") is not None else None
        })
        return _obj


