# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ExternalMatchSearchRequest(BaseModel):
    """
    ExternalMatchSearchRequest
    """ # noqa: E501
    dupr_id: Optional[StrictStr] = Field(default=None, alias="duprId")
    end_date: StrictInt = Field(description="The end date in epoch seconds", alias="endDate")
    event_format: Optional[List[StrictStr]] = Field(default=None, alias="eventFormat")
    limit: Optional[StrictInt] = None
    offset: Optional[StrictInt] = None
    start_date: StrictInt = Field(description="The start date in epoch seconds", alias="startDate")
    __properties: ClassVar[List[str]] = ["duprId", "endDate", "eventFormat", "limit", "offset", "startDate"]

    @field_validator('event_format')
    def event_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['DOUBLES', 'SINGLES']):
                raise ValueError("each list item must be one of ('DOUBLES', 'SINGLES')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalMatchSearchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalMatchSearchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "duprId": obj.get("duprId"),
            "endDate": obj.get("endDate"),
            "eventFormat": obj.get("eventFormat"),
            "limit": obj.get("limit"),
            "offset": obj.get("offset"),
            "startDate": obj.get("startDate")
        })
        return _obj


