# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from dupr_prod_httpx.models.provisional_rating import ProvisionalRating
from typing import Optional, Set
from typing_extensions import Self

class PlayerRatingResponse(BaseModel):
    """
    PlayerRatingResponse
    """ # noqa: E501
    default_rating: Optional[StrictStr] = Field(default=None, alias="defaultRating")
    doubles: Optional[StrictStr] = None
    doubles_provisional: Optional[StrictBool] = Field(default=None, alias="doublesProvisional")
    doubles_reliability_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="doublesReliabilityScore")
    doubles_verified: Optional[StrictStr] = Field(default=None, alias="doublesVerified")
    provisional_ratings: Optional[ProvisionalRating] = Field(default=None, alias="provisionalRatings")
    singles: Optional[StrictStr] = None
    singles_provisional: Optional[StrictBool] = Field(default=None, alias="singlesProvisional")
    singles_reliability_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="singlesReliabilityScore")
    singles_verified: Optional[StrictStr] = Field(default=None, alias="singlesVerified")
    __properties: ClassVar[List[str]] = ["defaultRating", "doubles", "doublesProvisional", "doublesReliabilityScore", "doublesVerified", "provisionalRatings", "singles", "singlesProvisional", "singlesReliabilityScore", "singlesVerified"]

    @field_validator('default_rating')
    def default_rating_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['DOUBLES', 'SINGLES']):
            raise ValueError("must be one of enum values ('DOUBLES', 'SINGLES')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlayerRatingResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of provisional_ratings
        if self.provisional_ratings:
            _dict['provisionalRatings'] = self.provisional_ratings.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlayerRatingResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "defaultRating": obj.get("defaultRating"),
            "doubles": obj.get("doubles"),
            "doublesProvisional": obj.get("doublesProvisional"),
            "doublesReliabilityScore": obj.get("doublesReliabilityScore"),
            "doublesVerified": obj.get("doublesVerified"),
            "provisionalRatings": ProvisionalRating.from_dict(obj["provisionalRatings"]) if obj.get("provisionalRatings") is not None else None,
            "singles": obj.get("singles"),
            "singlesProvisional": obj.get("singlesProvisional"),
            "singlesReliabilityScore": obj.get("singlesReliabilityScore"),
            "singlesVerified": obj.get("singlesVerified")
        })
        return _obj


