# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from dupr_prod_httpx.models.player_rating_response import PlayerRatingResponse
from dupr_prod_httpx.models.registration_response import RegistrationResponse
from dupr_prod_httpx.models.sponsor_logo_response import SponsorLogoResponse
from typing import Optional, Set
from typing_extensions import Self

class PlayerResponse(BaseModel):
    """
    PlayerResponse
    """ # noqa: E501
    age: Optional[StrictInt] = None
    display_username: Optional[StrictBool] = Field(default=None, alias="displayUsername")
    distance: Optional[StrictStr] = None
    distance_in_miles: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="distanceInMiles")
    dupr_id: StrictStr = Field(alias="duprId")
    email: StrictStr
    enable_privacy: Optional[StrictBool] = Field(default=None, alias="enablePrivacy")
    first_name: StrictStr = Field(alias="firstName")
    formatted_address: Optional[StrictStr] = Field(default=None, alias="formattedAddress")
    full_name: StrictStr = Field(alias="fullName")
    gender: Optional[StrictStr] = None
    hand: Optional[StrictStr] = None
    id: Optional[StrictInt] = None
    image_url: Optional[StrictStr] = Field(default=None, alias="imageUrl")
    invited: Optional[StrictBool] = None
    is_logged_in_user: Optional[StrictBool] = Field(default=None, alias="isLoggedInUser")
    is_player1: Optional[StrictBool] = Field(default=None, alias="isPlayer1")
    is_substitute: Optional[StrictBool] = Field(default=None, alias="isSubstitute")
    last_name: StrictStr = Field(alias="lastName")
    latitude: Optional[Union[StrictFloat, StrictInt]] = None
    longitude: Optional[Union[StrictFloat, StrictInt]] = None
    lucra_connected: Optional[StrictBool] = Field(default=None, alias="lucraConnected")
    partner_status: Optional[StrictStr] = Field(default=None, alias="partnerStatus")
    phone: Optional[StrictStr] = None
    ratings: Optional[PlayerRatingResponse] = None
    registered: StrictBool
    registration_details: RegistrationResponse = Field(alias="registrationDetails")
    registration_type: StrictStr = Field(alias="registrationType")
    short_address: Optional[StrictStr] = Field(default=None, alias="shortAddress")
    show_rating_banner: Optional[StrictBool] = Field(default=None, alias="showRatingBanner")
    sponsor: Optional[SponsorLogoResponse] = None
    status: Optional[StrictStr] = None
    substitution_details: Optional[List[PlayerResponse]] = Field(default=None, alias="substitutionDetails")
    team_status: Optional[StrictStr] = Field(default=None, alias="teamStatus")
    username: Optional[StrictStr] = None
    verified_email: Optional[StrictBool] = Field(default=None, alias="verifiedEmail")
    __properties: ClassVar[List[str]] = ["age", "displayUsername", "distance", "distanceInMiles", "duprId", "email", "enablePrivacy", "firstName", "formattedAddress", "fullName", "gender", "hand", "id", "imageUrl", "invited", "isLoggedInUser", "isPlayer1", "isSubstitute", "lastName", "latitude", "longitude", "lucraConnected", "partnerStatus", "phone", "ratings", "registered", "registrationDetails", "registrationType", "shortAddress", "showRatingBanner", "sponsor", "status", "substitutionDetails", "teamStatus", "username", "verifiedEmail"]

    @field_validator('gender')
    def gender_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['FEMALE', 'MALE']):
            raise ValueError("must be one of enum values ('FEMALE', 'MALE')")
        return value

    @field_validator('hand')
    def hand_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['BOTH', 'LEFT', 'NONE', 'RIGHT']):
            raise ValueError("must be one of enum values ('BOTH', 'LEFT', 'NONE', 'RIGHT')")
        return value

    @field_validator('partner_status')
    def partner_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACTIVE', 'CANCELLED', 'COMPLETE', 'CONFIRMED', 'DELETED', 'FORFEITED', 'INACTIVE', 'INVITED', 'IN_PROGRESS', 'MATCH_BYE', 'NOT_CONFIRMED', 'ONGOING', 'PENDING', 'SUSPENDED_TOS_13', 'UPCOMING']):
            raise ValueError("must be one of enum values ('ACTIVE', 'CANCELLED', 'COMPLETE', 'CONFIRMED', 'DELETED', 'FORFEITED', 'INACTIVE', 'INVITED', 'IN_PROGRESS', 'MATCH_BYE', 'NOT_CONFIRMED', 'ONGOING', 'PENDING', 'SUSPENDED_TOS_13', 'UPCOMING')")
        return value

    @field_validator('registration_type')
    def registration_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['INVITATION', 'UNCLAIMED']):
            raise ValueError("must be one of enum values ('INVITATION', 'UNCLAIMED')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACTIVE', 'CANCELLED', 'COMPLETE', 'CONFIRMED', 'DELETED', 'FORFEITED', 'INACTIVE', 'INVITED', 'IN_PROGRESS', 'MATCH_BYE', 'NOT_CONFIRMED', 'ONGOING', 'PENDING', 'SUSPENDED_TOS_13', 'UPCOMING']):
            raise ValueError("must be one of enum values ('ACTIVE', 'CANCELLED', 'COMPLETE', 'CONFIRMED', 'DELETED', 'FORFEITED', 'INACTIVE', 'INVITED', 'IN_PROGRESS', 'MATCH_BYE', 'NOT_CONFIRMED', 'ONGOING', 'PENDING', 'SUSPENDED_TOS_13', 'UPCOMING')")
        return value

    @field_validator('team_status')
    def team_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACTIVE', 'CANCELLED', 'COMPLETE', 'CONFIRMED', 'DELETED', 'FORFEITED', 'INACTIVE', 'INVITED', 'IN_PROGRESS', 'MATCH_BYE', 'NOT_CONFIRMED', 'ONGOING', 'PENDING', 'SUSPENDED_TOS_13', 'UPCOMING']):
            raise ValueError("must be one of enum values ('ACTIVE', 'CANCELLED', 'COMPLETE', 'CONFIRMED', 'DELETED', 'FORFEITED', 'INACTIVE', 'INVITED', 'IN_PROGRESS', 'MATCH_BYE', 'NOT_CONFIRMED', 'ONGOING', 'PENDING', 'SUSPENDED_TOS_13', 'UPCOMING')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlayerResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ratings
        if self.ratings:
            _dict['ratings'] = self.ratings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of registration_details
        if self.registration_details:
            _dict['registrationDetails'] = self.registration_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sponsor
        if self.sponsor:
            _dict['sponsor'] = self.sponsor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in substitution_details (list)
        _items = []
        if self.substitution_details:
            for _item_substitution_details in self.substitution_details:
                if _item_substitution_details:
                    _items.append(_item_substitution_details.to_dict())
            _dict['substitutionDetails'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlayerResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "age": obj.get("age"),
            "displayUsername": obj.get("displayUsername"),
            "distance": obj.get("distance"),
            "distanceInMiles": obj.get("distanceInMiles"),
            "duprId": obj.get("duprId"),
            "email": obj.get("email"),
            "enablePrivacy": obj.get("enablePrivacy"),
            "firstName": obj.get("firstName"),
            "formattedAddress": obj.get("formattedAddress"),
            "fullName": obj.get("fullName"),
            "gender": obj.get("gender"),
            "hand": obj.get("hand"),
            "id": obj.get("id"),
            "imageUrl": obj.get("imageUrl"),
            "invited": obj.get("invited"),
            "isLoggedInUser": obj.get("isLoggedInUser"),
            "isPlayer1": obj.get("isPlayer1"),
            "isSubstitute": obj.get("isSubstitute"),
            "lastName": obj.get("lastName"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "lucraConnected": obj.get("lucraConnected"),
            "partnerStatus": obj.get("partnerStatus"),
            "phone": obj.get("phone"),
            "ratings": PlayerRatingResponse.from_dict(obj["ratings"]) if obj.get("ratings") is not None else None,
            "registered": obj.get("registered"),
            "registrationDetails": RegistrationResponse.from_dict(obj["registrationDetails"]) if obj.get("registrationDetails") is not None else None,
            "registrationType": obj.get("registrationType"),
            "shortAddress": obj.get("shortAddress"),
            "showRatingBanner": obj.get("showRatingBanner"),
            "sponsor": SponsorLogoResponse.from_dict(obj["sponsor"]) if obj.get("sponsor") is not None else None,
            "status": obj.get("status"),
            "substitutionDetails": [PlayerResponse.from_dict(_item) for _item in obj["substitutionDetails"]] if obj.get("substitutionDetails") is not None else None,
            "teamStatus": obj.get("teamStatus"),
            "username": obj.get("username"),
            "verifiedEmail": obj.get("verifiedEmail")
        })
        return _obj

# TODO: Rewrite to not use raise_errors
PlayerResponse.model_rebuild(raise_errors=False)

