# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from dupr_prod_httpx.models.participant import Participant
from typing import Optional, Set
from typing_extensions import Self

class RegistrationResponse(BaseModel):
    """
    RegistrationResponse
    """ # noqa: E501
    event_refunded_amount: Union[StrictFloat, StrictInt] = Field(alias="eventRefundedAmount")
    is_participant1: StrictBool = Field(alias="isParticipant1")
    is_wait_listed: StrictBool = Field(alias="isWaitListed")
    player1: Optional[Participant] = None
    player2: Optional[Participant] = None
    registration_id: StrictInt = Field(alias="registrationId")
    __properties: ClassVar[List[str]] = ["eventRefundedAmount", "isParticipant1", "isWaitListed", "player1", "player2", "registrationId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RegistrationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of player1
        if self.player1:
            _dict['player1'] = self.player1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of player2
        if self.player2:
            _dict['player2'] = self.player2.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RegistrationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eventRefundedAmount": obj.get("eventRefundedAmount"),
            "isParticipant1": obj.get("isParticipant1"),
            "isWaitListed": obj.get("isWaitListed"),
            "player1": Participant.from_dict(obj["player1"]) if obj.get("player1") is not None else None,
            "player2": Participant.from_dict(obj["player2"]) if obj.get("player2") is not None else None,
            "registrationId": obj.get("registrationId")
        })
        return _obj


