# coding: utf-8

# flake8: noqa

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ApiRegistrationApi",
    "AuthenticationApi",
    "ClubApi",
    "MatchApi",
    "PlayerApi",
    "PlayerRatingApi",
    "UsersApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ArrayWrapperOfExternalUserDetailResponse",
    "ArrayWrapperOfPlayerResponse",
    "ClientHookRequest",
    "CreateProvisionalRatingRequest",
    "DeleteProvisionalRatingRequest",
    "ExternalAgeRangeFilter",
    "ExternalClubMemberRequest",
    "ExternalDeleteMatchRequest",
    "ExternalFilterLocation",
    "ExternalInviteRequest",
    "ExternalMatchRequest",
    "ExternalMatchSearchRequest",
    "ExternalMatchTeam",
    "ExternalRatingFilter",
    "ExternalSearchFilter",
    "ExternalSearchRequest",
    "ExternalUpdateMatchRequest",
    "ExternalUserDetailResponse",
    "ExternalUserPerformance",
    "ExternalUserRatingResponse",
    "FindDuprIdByEmailRequest",
    "GetProvisionalRatingRequest",
    "Participant",
    "PlayerRatingResponse",
    "PlayerResponse",
    "PlayersSortedRequest",
    "ProvisionalRating",
    "RatingCoach",
    "RegistrationResponse",
    "SingleWrapperOfTokenResponse",
    "SponsorLogoResponse",
    "TokenResponse",
    "UpdateProvisionalRatingRequest",
    "WinLossCount",
]

# import apis into sdk package
from dupr_prod_httpx.api.api_registration_api import ApiRegistrationApi as ApiRegistrationApi
from dupr_prod_httpx.api.authentication_api import AuthenticationApi as AuthenticationApi
from dupr_prod_httpx.api.club_api import ClubApi as ClubApi
from dupr_prod_httpx.api.match_api import MatchApi as MatchApi
from dupr_prod_httpx.api.player_api import PlayerApi as PlayerApi
from dupr_prod_httpx.api.player_rating_api import PlayerRatingApi as PlayerRatingApi
from dupr_prod_httpx.api.users_api import UsersApi as UsersApi

# import ApiClient
from dupr_prod_httpx.api_response import ApiResponse as ApiResponse
from dupr_prod_httpx.api_client import ApiClient as ApiClient
from dupr_prod_httpx.configuration import Configuration as Configuration
from dupr_prod_httpx.exceptions import OpenApiException as OpenApiException
from dupr_prod_httpx.exceptions import ApiTypeError as ApiTypeError
from dupr_prod_httpx.exceptions import ApiValueError as ApiValueError
from dupr_prod_httpx.exceptions import ApiKeyError as ApiKeyError
from dupr_prod_httpx.exceptions import ApiAttributeError as ApiAttributeError
from dupr_prod_httpx.exceptions import ApiException as ApiException

# import models into sdk package
from dupr_prod_httpx.models.array_wrapper_of_external_user_detail_response import ArrayWrapperOfExternalUserDetailResponse as ArrayWrapperOfExternalUserDetailResponse
from dupr_prod_httpx.models.array_wrapper_of_player_response import ArrayWrapperOfPlayerResponse as ArrayWrapperOfPlayerResponse
from dupr_prod_httpx.models.client_hook_request import ClientHookRequest as ClientHookRequest
from dupr_prod_httpx.models.create_provisional_rating_request import CreateProvisionalRatingRequest as CreateProvisionalRatingRequest
from dupr_prod_httpx.models.delete_provisional_rating_request import DeleteProvisionalRatingRequest as DeleteProvisionalRatingRequest
from dupr_prod_httpx.models.external_age_range_filter import ExternalAgeRangeFilter as ExternalAgeRangeFilter
from dupr_prod_httpx.models.external_club_member_request import ExternalClubMemberRequest as ExternalClubMemberRequest
from dupr_prod_httpx.models.external_delete_match_request import ExternalDeleteMatchRequest as ExternalDeleteMatchRequest
from dupr_prod_httpx.models.external_filter_location import ExternalFilterLocation as ExternalFilterLocation
from dupr_prod_httpx.models.external_invite_request import ExternalInviteRequest as ExternalInviteRequest
from dupr_prod_httpx.models.external_match_request import ExternalMatchRequest as ExternalMatchRequest
from dupr_prod_httpx.models.external_match_search_request import ExternalMatchSearchRequest as ExternalMatchSearchRequest
from dupr_prod_httpx.models.external_match_team import ExternalMatchTeam as ExternalMatchTeam
from dupr_prod_httpx.models.external_rating_filter import ExternalRatingFilter as ExternalRatingFilter
from dupr_prod_httpx.models.external_search_filter import ExternalSearchFilter as ExternalSearchFilter
from dupr_prod_httpx.models.external_search_request import ExternalSearchRequest as ExternalSearchRequest
from dupr_prod_httpx.models.external_update_match_request import ExternalUpdateMatchRequest as ExternalUpdateMatchRequest
from dupr_prod_httpx.models.external_user_detail_response import ExternalUserDetailResponse as ExternalUserDetailResponse
from dupr_prod_httpx.models.external_user_performance import ExternalUserPerformance as ExternalUserPerformance
from dupr_prod_httpx.models.external_user_rating_response import ExternalUserRatingResponse as ExternalUserRatingResponse
from dupr_prod_httpx.models.find_dupr_id_by_email_request import FindDuprIdByEmailRequest as FindDuprIdByEmailRequest
from dupr_prod_httpx.models.get_provisional_rating_request import GetProvisionalRatingRequest as GetProvisionalRatingRequest
from dupr_prod_httpx.models.participant import Participant as Participant
from dupr_prod_httpx.models.player_rating_response import PlayerRatingResponse as PlayerRatingResponse
from dupr_prod_httpx.models.player_response import PlayerResponse as PlayerResponse
from dupr_prod_httpx.models.players_sorted_request import PlayersSortedRequest as PlayersSortedRequest
from dupr_prod_httpx.models.provisional_rating import ProvisionalRating as ProvisionalRating
from dupr_prod_httpx.models.rating_coach import RatingCoach as RatingCoach
from dupr_prod_httpx.models.registration_response import RegistrationResponse as RegistrationResponse
from dupr_prod_httpx.models.single_wrapper_of_token_response import SingleWrapperOfTokenResponse as SingleWrapperOfTokenResponse
from dupr_prod_httpx.models.sponsor_logo_response import SponsorLogoResponse as SponsorLogoResponse
from dupr_prod_httpx.models.token_response import TokenResponse as TokenResponse
from dupr_prod_httpx.models.update_provisional_rating_request import UpdateProvisionalRatingRequest as UpdateProvisionalRatingRequest
from dupr_prod_httpx.models.win_loss_count import WinLossCount as WinLossCount

